### ISSUE TITLE
Use ReactiveUI.Fody instead of wordy props

### ISSUE THREAD

**Issue by worldbeater** [egramtel/egram.tel#14]
See https://github.com/egramtel/egram.tel/pull/10

**Comment by x2bool** [comment]
Hi! I added ReactiveUI.Fody package https://github.com/egramtel/egram.tel/pull/18 but at compile time it gives me this error:

```
  Tel.Egram.Components.Navigation: [] Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver /Users/sergeykhabibullin/.nuget/packages/reactiveui.fody/8.3.1/netstandardweaver/ReactiveUI.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 208
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 104
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Value cannot be null.
Parameter name: self
Type:
System.ArgumentNullException
StackTrace:
   at Mono.Cecil.Rocks.TypeDefinitionRocks.GetConstructors(TypeDefinition self)
   at ReactiveUI.Fody.ObservableAsPropertyWeaver.Execute()
   at ReactiveUI.Fody.ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 204
Source:
Mono.Cecil.Rocks
TargetSite:
System.Collections.Generic.IEnumerable`1[Mono.Cecil.MethodDefinition] GetConstructors(Mono.Cecil.TypeDefinition)
```

Any ideas what could be wrong?

**Comment by x2bool** [comment]
Hmm. https://github.com/egramtel/egram.tel/pull/18/files#diff-30baf0d7261978bc23a8e08dc3218a8a

Is something not right?

**Comment by x2bool** [comment]
I've added FodyWeavers to every project that references ReactiveUI.Fody, still got this error. https://github.com/egramtel/egram.tel/tree/feature/reactiveui-fody

**Comment by worldbeater** [comment]
Insteresting. I've just cloned <a href="https://github.com/egramtel/egram.tel/pull/18/commits/c6bb5752cf2507a99434b14b9cbdfb301c7c4040">this commit</a> and it worked on my Windows machine.

**Comment by x2bool** [comment]
Closed by https://github.com/egramtel/egram.tel/pull/23
