### ISSUE TITLE
Can't select chat after login

### ISSUE THREAD

**Issue by Liminiens** [egramtel/egram.tel#17]
After login chat selection doesnt work and messages shown are mixed from all chats.

![2018-09-08_13-12-19](https://user-images.githubusercontent.com/10695322/45253035-fac53900-b368-11e8-8953-df476e40f311.gif)

Built from ea074db0485c85260634b058e283c6a9fb16be69.

```
dotnet --version
2.1.401
```

**Comment by x2bool** [comment]
This should be fixed now.
