### ISSUE TITLE
Add CI infrastructure

### ISSUE THREAD

**Issue by ForNeVeR** [egramtel/egram.tel#19]
- [x] Cross-platform unit tests
  - [x] macOS
  - [x] Linux
  - [x] Windows
- [x] Release builder and uploader
  - [x] Windows
  - [x] I don't know if we want to prepare packages for other OS, so for now I'd leave that

**Comment by x2bool** [comment]
https://github.com/qmfrederik/dotnet-packaging - could be useful. It lacks Mac support, but I could fix that in the future

**Comment by x2bool** [comment]
This is finally resolved
