### ISSUE TITLE
No channels/messages are visible and can't send any

### ISSUE THREAD

**Issue by Trapov** [egramtel/egram.tel#25]
I think it's somehow connected to the #17 issue, but mine is rather different, I have a few in fact:
* I can't see any channels in the first tab:
![image](https://user-images.githubusercontent.com/13402883/45921691-9612ee00-bed3-11e8-8ceb-953531eb9707.png)
* I can see group channels, but can't send any messages and see them
![image](https://user-images.githubusercontent.com/13402883/45921707-1b969e00-bed4-11e8-9d7d-c11e88f9859c.png)

```
dotnet --version
2.1.402
```

**Comment by x2bool** [comment]
Hi! This will be fixed after I implement this: https://github.com/AvaloniaUI/Avalonia/issues/1909

We could fix this without implementing smooth scrolling but it will be broken in other ways, so it's better to wait a little bit.

**Comment by x2bool** [comment]
This should be fixed now
