### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by ForNeVeR** [egramtel/egram.tel#4]
Many of our users cannot use egram.tel because it doesn't support proxy.

Let's add the following (each feature could be implemented in order):

- [x] add a settings dialog to set up the proxy

**Comment by x2bool** [comment]
Sure! TDLib supports proxy. Helpful links:
https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L1772
https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L2856

**Comment by x2bool** [comment]
New link for 1.3: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L3339

**Comment by x2bool** [comment]
Proxy support probably should be implemented in 2 places: on auth page and on settings page so users could add proxy before login???

**Comment by x2bool** [comment]
I've finally reimplemented proxy popup and it's working now as intended.
