### ISSUE TITLE
Portable version for Windows?

### ISSUE THREAD

**Issue by Twilightssuperb** [egramtel/egram.tel#42]
I'm glad to finally see releases with EXE-files, but I'll be happy with portable (7Z or ZIP) one, because I don't wanna install egram.tel, I just wanna unpack it archive and use.

**Comment by x2bool** [comment]
That seems reasonable. I'll do that.

However you should know that the installer does nothing but extracts files into target directory.

**Comment by x2bool** [comment]
Done!
