### ISSUE TITLE
setting button doesnt work 

### ISSUE THREAD

**Issue by lo2lo2a82** [egramtel/egram.tel#44]
windows v settings doesnt work 

Arabic messages looks like weird symbols 
![2019-01-12 18_58_54-](https://user-images.githubusercontent.com/31206976/51076040-2d2ace00-169c-11e9-8f00-7b03321771df.png)

**Comment by lo2lo2a82** [comment]
so you are gone add support to Arabic text ? i hope you do 

waiting to see the app in it s final version 

good luck and thanks for replying

**Comment by x2bool** [comment]
Thanks. Yes, ideally all languages should be supported. However this depends on underlying framework. Issues like this: https://github.com/AvaloniaUI/Avalonia/issues/1809 should be solved before we could make it work.

**Comment by lo2lo2a82** [comment]
happy to know that ... thank you 

i ll follow your next beta and tell if i have any problem ... good luck

**Comment by lo2lo2a82** [comment]
happy to know that ... thank you 

i ll follow your next beta and tell if i have any problem ... good luck
