### ISSUE TITLE
Viewing Self Destructing Photo caused my account and phone number banned

### ISSUE THREAD

**Issue by samirdev2** [egramtel/egram.tel#49]
Hi

My friend sent me a self destructing photo. After seeing the photo in the Egram. Photo not be deleted. And after seeing the same picture on my Android phone my account banned!!!!
When I trying to sign-up again, I get "Your phone number is banned".

**Comment by Bannerets** [comment]
Most likely that's not related to self-destructing photos. Telegram's anti-spam system just sometimes does accidental bans. Write to recover@telegram.org to recover your account.

See https://github.com/tdlib/td/issues/458 and https://github.com/tdlib/td/issues/480.

Aside of this, self-destructing timer is available only in secret chats, and Egram doesn't support those yet, how is that possible?

**Comment by x2bool** [comment]
I am closing this for now. There is no support for self-destructing photos yet, so this isn't likely to be the reason for your ban. Feel free to provide more details.
