### ISSUE TITLE
early opinion

### ISSUE THREAD

**Issue by kirsan31** [egramtel/egram.tel#5]
First of all - great work! Telegram on c# - at last :+1: 
Sadly, it's nearly unusable on windows :( And the problem is avalonia. It's very slow on win :( Many rendering problems and bugs, I hope, will be fixed in the future. But whole concept? Even simple avalonia ui are working slow. It's working incredibly slow even compare to web apps :(((( Is it only windows problems, and on Nix/macOs all ok?
Do you have any thoughts on this?

**Comment by x2bool** [comment]
Yeah! You're right. There are performance issues and Avalonia can be buggy sometimes. The team behind Avalonia says there are still lots of things to optimize, so let's hope performance will be better in the future. Also I am on Mac, and I didn't know about certain problems on Windows, so you can expect that some of the problems will be solved.

**Comment by x2bool** [comment]
With recent update Avalonia got a lot faster. Feel free to report bad performance again if you see it.
