### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by oripio** [egramtel/egram.tel#54]
oripio@oripio-pc:/opt/egram.tel/src/Tel.Egram$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Services/Tel.Egram.Services.csproj : warning NU1603: Tel.Egram.Services depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
  Restore completed in 44,35 ms for /opt/egram.tel/src/Tel.Egram.Services/Tel.Egram.Services.csproj.
  Restore completed in 44,34 ms for /opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj.
  Restore completed in 44,34 ms for /opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj.
  Restore completed in 44,34 ms for /opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj.
  Restore completed in 30,28 ms for /opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Native (>= 0.7.1-build1258-beta) but Avalonia.Native 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Native 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
  Restore completed in 6,58 ms for /opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Native (>= 0.7.1-build1258-beta) but Avalonia.Native 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Native 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Services/Tel.Egram.Services.csproj : warning NU1603: Tel.Egram.Services depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
  Tel.Egram.Services -> /opt/egram.tel/src/Tel.Egram.Services/bin/Debug/netstandard2.0/Tel.Egram.Services.dll
    Fody: Fody (version 3.2.9.0) Executing
    Fody: Searched for 'PropertyChanged'. Found: /home/oripio/.nuget/packages/propertychanged.fody/2.5.13/build/../netstandardweaver/PropertyChanged.Fody.dll
    Fody:   Finished Fody 88ms.
  Tel.Egram.Model -> /opt/egram.tel/src/Tel.Egram.Model/bin/Debug/netstandard2.0/Tel.Egram.Model.dll
    Fody:   Skipped Verifying assembly since it is disabled in configuration
Application/NotificationLogic.cs(53,68): error CS0246: The type or namespace name 'PixelRect' could not be found (are you missing a using directive or an assembly reference?) [/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj]
Application/NotificationLogic.cs(64,68): error CS0246: The type or namespace name 'PixelRect' could not be found (are you missing a using directive or an assembly reference?) [/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj]

Build FAILED.

/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram.Services/Tel.Egram.Services.csproj : warning NU1603: Tel.Egram.Services depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved. [/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj]
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Native (>= 0.7.1-build1258-beta) but Avalonia.Native 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Native 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.Native (>= 0.7.1-build1258-beta) but Avalonia.Native 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Native 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram/Tel.Egram.csproj : warning NU1603: Tel.Egram depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Model/Tel.Egram.Model.csproj : warning NU1603: Tel.Egram.Model depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Services/Tel.Egram.Services.csproj : warning NU1603: Tel.Egram.Services depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Application/Tel.Egram.Application.csproj : warning NU1603: Tel.Egram.Application depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia (>= 0.7.1-build1258-beta) but Avalonia 0.7.1-build1258-beta was not found. An approximate best match of Avalonia 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.Desktop (>= 0.7.1-build1258-beta) but Avalonia.Desktop 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.Desktop 0.7.1-build957-beta was resolved.
/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj : warning NU1603: Tel.Egram.Views depends on Avalonia.ReactiveUI (>= 0.7.1-build1258-beta) but Avalonia.ReactiveUI 0.7.1-build1258-beta was not found. An approximate best match of Avalonia.ReactiveUI 0.7.1-build957-beta was resolved.
**Application/NotificationLogic.cs(53,68): error CS0246: The type or namespace name 'PixelRect' could not be found (are you missing a using directive or an assembly reference?) [/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj]
Application/NotificationLogic.cs(64,68): error CS0246: The type or namespace name 'PixelRect' could not be found (are you missing a using directive or an assembly reference?) [/opt/egram.tel/src/Tel.Egram.Views/Tel.Egram.Views.csproj]**
    26 Warning(s)
    **2 Error(s)**

Time Elapsed 00:00:03.68
oripio@oripio-pc:/opt/egram.tel/src/Tel.Egram$

**Comment by x2bool** [comment]
Yeah! This is probably because of the deleted 0.7.x packages of Avalonia. I'll upgrade packages.

**Comment by x2bool** [comment]
Avalonia is now 0.8.0.
